thevar = [
{'quote': 'May the Force be with you', 'source': 'Star Wars', 'speaker': 'Obi-Wan Kenobi'},
{'quote': 'Even the smallest person can change the course of the future.', 'source': 'The Fellowship of the Ring', 'speaker': 'Gandalf the Grey'},
{'quote': "Roads?  Where we're going, we don't need roads.", 'source': 'Back to the Future', 'speaker': 'Doc Brown'},
{'quote': "Your scientists were so preoccupied with whether or not they could, they didn't stop to think if the should.", 'source': 'Jurassic Park', 'speaker': 'Ian Malcom'},
{'quote': "I'll be back.", 'source': 'The Terminator', 'speaker': 'T-800'},
{'quote': 'A day may come when the courage of men fails, when we forget our friends and forsake all bonds of fellowship.  But it is not this day!', 'source': 'The Return of the King', 'speaker': 'Aragorn'},
{'quote': 'Do.  Or do not.  There is no try.', 'source': 'The Empire Strikes Back', 'speaker': 'Yoda'},
{'quote': "I have come here to chew bubblegum and kick ass...And I'm all out of bubblegum.", 'source': 'They Live', 'speaker': 'John Nada'},
{'quote': "Great,kid!  Don't get cocky.", 'source': 'Star Wars', 'speaker': 'Han Solo'},
{'quote': "By Grabthar's hammer, by the suns of Worvan, you shall be avenged.", 'source': 'Galaxy Quest', 'speaker': 'Dr. Lazarus (Sir Alexander Dane)'},
{'quote': 'Take your stinking paws off me, you damn dirty ape!', 'source': 'Planet of the Apes', 'speaker': 'Taylor'},
{'quote': "I'm sorry Dave.  I'm afraid I can't do that.", 'source': '2001: A Space Odyssey', 'speaker': 'HAL 9000'},
{'quote': 'Klaatu barada nikto.', 'source': 'The Day the Earth Stood Still', 'speaker': 'Klaatu'},
{'quote': 'Khaaaaaaan', 'source': 'The Wrath of Khan', 'speaker': 'James T. Kirk'},
{'quote': "The universe is a pretty big place.  It's bigger than anything anyone has ever dreamed of before.  So if it's just us...seems like an awful waste of space.  Right?", 'source': 'Contact', 'speaker': 'Carl Sagan'},
{'quote': 'No, I am your father.', 'source': 'The Empire Strikes Back', 'speaker': 'Darth Vader'},
{'quote': 'I will take the ring to Mordor, though I do not know the way.', 'source': 'The Fellowship of the Ring', 'speaker': 'Frodo Baggins'},
{'quote': "I've seen things you people wouldn't believe.  Attack ships on fire off the shoulder of Orion.  I watched C-beams glitter in the dark near the Tannhauser gate.  All those moments will be lost in time...like tears in the rain.  Time to die.", 'source': 'Blade Runner', 'speaker': 'Roy Batty'},
{'quote': 'What is best in life?\n\nTo crush your enemies, see them driven before you, and to hear the lamentation of their women.', 'source': 'Conan the Barbarian', 'speaker': 'Mongol General \\ Conan'},
{'quote': 'Revenge is a dish best served cold', 'source': 'Star Trek II: The Wrath of Khan', 'speaker': 'Khan Noonien Singh'},
{'quote': 'Two men enter, one man leaves.', 'source': 'Mad Max III: Beyond Thunderdome', 'speaker': 'Auntie Entity'},
{'quote': 'Hello there!', 'source': 'Star Wars', 'speaker': 'Obi-Wan Kenobi'},
{'quote': "It's a trap!", 'source': 'Return of the Jedi', 'speaker': 'Admiral Akbar'},
{'quote': "These aren't the droids you're looking for.", 'source': 'Star Wars', 'speaker': 'Obi-Wan Kenobi'},
{'quote': 'This is how liberty dies...with thunderous applause.', 'source': 'Revenge of the Sith', 'speaker': 'Padme Amidala'},
{'quote': "Who's the more foolish?  The fool or the fool who follows him?", 'source': 'Star Wars', 'speaker': 'Obi-Wan Kenobi'},
{'quote': 'Fear leads to anger, anger leads to hate, hate leads to suffering.', 'source': 'The Phantom Menace', 'speaker': 'Yoda'},
{'quote': "Help me Obi-Wan Kenobi.  You're my only hope.", 'source': 'Star Wars', 'speaker': 'Princess Lea'},
{'quote': 'This is the weapon of a Jedi Knight.  Not as clumsy or random as a blaster; an elegant weapon for a more civilized age.', 'source': 'Star Wars', 'speaker': 'Obi-Wan Kenobi'},
{'quote': 'Mos Eisley spaceport.  You will never find a more wretched hive of scum and villainy.', 'source': 'Star Wars', 'speaker': 'Obi-Wan Kenobi'},
{'quote': "You can't win Darth.  If you strike me down, I shall become more powerful than you can imagine.", 'source': 'Star Wars', 'speaker': 'Obi-Wan Kenobi'},
{'quote': "I killed them all.  They're dead, every single one of them.  And not just the men, but the women and the children too.  They're like animals, and I slaughtered them like animals.  I hate them!", 'source': 'Revenge of the Sith', 'speaker': 'Anakin Skywalker'},
{'quote': "It's a dangerous business, Frodo, going out your door.  You step onto the road, and if you don't keep your feet, there's no knowing where you might be swept off to.", 'source': 'The Fellowship of the Ring', 'speaker': 'Bilbo Baggins'},
{'quote': "End?  No, the journey doesn't end here.  Death is just another path, one that we all must take.  The grey rain-curtain of this world rolls back, and all turns to silver glass, and then you see it.  What? Gandalf? See what?  White shores, and beyond, a far green country under a swift sunrise.", 'source': 'The Return of the King', 'speaker': 'Gandalf the White'},
{'quote': 'I wish the ring had never come to me.  I wish non of this had happened.\n\nSo do all who live to see such times, but that is not for them to decide.  All we have to decide is what to do with the time that is given to us.', 'source': 'The Fellowship of the Ring', 'speaker': 'Frodo Baggins \\ Gandalf the Grey'},
{'quote': "I don't know half of you half as well as I should like; and I like less than half of you half as well as you deserve.", 'source': 'The Fellowship of the Ring', 'speaker': 'Bilbo Baggins'},
{'quote': 'A wizard is never late, Frodo Baggins.  Nor is he early.  He arrives precisely when he means to.', 'source': 'The Fellowship of the Ring', 'speaker': 'Gandalf the Grey'},
{'quote': 'In a hole in the ground there lived a hobbit.  Not a nasty, dirty, wet hole, filled with the ends of worms and an oozy smell, nor yet a dry, bare sandy hole with noting in it to sit down on or to eat: it was a hobbit-hole, and that means comfort.', 'source': 'The Hobbit', 'speaker': 'J.R.R. Tolkein'},
{'quote': 'Well, here at last, dear friends, on the shores of the sea comes the end of our fellowship in middle-earth.  Go in peace! I will not say: do not weep for not all tears are an evil.', 'source': 'The Return of the King', 'speaker': 'Gandalf the White'},
{'quote': 'All that is gold does not glitter, Not all those who wander are lost; The old that is strong does not wither, Deep roots are not reached by the frost.', 'source': 'The Fellowship of the Ring', 'speaker': 'Aragorn'},
{'quote': 'It is not despair, for despair is only for those who see the end beyond all doubt.  We do not.', 'source': 'The Fellowship of the Ring', 'speaker': 'Gandalf the Grey'},
{'quote': 'We are always more afraid than we wish to be, but we can always be braver than we expect.', 'source': 'The Wheel of Time', 'speaker': 'Robert Jordan'},
{'quote': 'Of my friend, I can only say this.  Of all the souls I have encountered in my travels, his was the most human.', 'source': 'Star Trek II: The Wrath of Khan', 'speaker': 'James T. Kirk'},
{'quote': 'Klingons do not procrastinate.  It is a tactical delay.', 'source': 'Star Trek: TNG', 'speaker': 'Worf'},
{'quote': 'A warrior does not let a friend face danger alone.', 'source': 'Star Trek: TNG', 'speaker': 'Worf'},
{'quote': "I haven't faced death.  I've cheated death.  I've tricked my way out of death and patted myself on the back for my ingenuity; I know nothing.", 'source': 'Star Trek II: The Wrath of Khan', 'speaker': 'James T. Kirk'},
{'quote': 'With the first link, the chain is forged.  The first speech censored, the first thought forbidden, the first freedom denied, chains us all irrevocably.', 'source': 'Star Trek: TNG', 'speaker': 'Jean-Luc Picard'},
{'quote': 'I have been and always shall be your friend.', 'source': 'Star Trek', 'speaker': 'Spock'},
{'quote': 'Live long and prosper.', 'source': 'Star Trek', 'speaker': 'Spock'},
{'quote': 'I am glad you are here with me.  Here at the end of all things.', 'source': 'Return of the King', 'speaker': 'Frodo Baggins'},
{'quote': 'Oft hope is born when all is forlorn.', 'source': 'Return of the King', 'speaker': 'Legolas'},
{'quote': 'We have hope. Rebellions are built on hope!', 'source': 'Rogue One', 'speaker': 'Jin Erso'},
{'quote': 'I am a Jedi, like my father before me.', 'source': 'The Return of the Jedi', 'speaker': 'Luke Skywalker'},
{'quote': 'You cannot pass, I am a servant of the Secret Fire, wielder of the flame of Anor.  You cannot pass.  The dark fire will not avail you, flame of Udûn.  Go back to the Shadow!  You cannot pass.', 'source': 'The Fellowship of the Ring', 'speaker': 'Gandalf the Grey'},
{'quote': 'Many that live deserve death and some that die deserve life.  Can you give it to them?  Then do not be so eager to deal out death in judgement.  For even the wise cannot see all ends.', 'source': 'The Fellowship of the Ring', 'speaker': 'Gandalf the Grey'},
]
